# Copyright (c) 2019-2026 Truestamp, Inc.
# SPDX-License-Identifier: MIT

version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - go
    open-pull-requests-limit: 10
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"
