# Copyright (c) 2021-2026 Truestamp, Inc.
# SPDX-License-Identifier: MIT

name: Feature Request
description: Suggest an idea for the Truestamp CLI
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What are you trying to accomplish? What goes wrong with the current behavior?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: textarea
    id: additional
    attributes:
      label: Additional context
