// Copyright (c) 2019-2026 Truestamp, Inc.
// SPDX-License-Identifier: MIT

package cmd

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"github.com/truestamp/truestamp-cli/internal/encoding"
	"github.com/truestamp/truestamp-cli/internal/entropy"
	"github.com/truestamp/truestamp-cli/internal/hashing"
	"github.com/truestamp/truestamp-cli/internal/introspect"
	"github.com/truestamp/truestamp-cli/internal/proof"
	"github.com/truestamp/truestamp-cli/internal/proof/ptype"
	"github.com/truestamp/truestamp-cli/internal/ui"
)

// `schema` is a namespace, not a resource group: it owns no server
// records. It still uses `list` and `get` because it owns an enumerable
// registry, which R0 permits. See kb/command-tree.md.
//
// Everything it emits is generated from the live cobra tree or from the
// in-code registries, never from a hand-maintained copy, so it cannot
// drift from the binary that prints it.

var schemaCmd = &cobra.Command{
	Use:   "schema",
	Short: "Read-only: the command tree and registries",
	Long: `Machine-readable descriptions of this binary's own interface.

Everything here is generated by walking the live command tree and the
in-code registries, so it always describes the binary you are running.

  truestamp schema list                  the available documents
  truestamp schema get commands --json   the whole command tree
  truestamp schema get algorithms        the hash algorithm registry

'schema get commands --json' is the one call that answers "what can this
CLI do, and with which flags" without parsing help text.`,
}

var schemaListCmd = &cobra.Command{
	Use:   "list",
	Short: "List the available schema documents",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		jsonOut, silent := outputMode(cmd)
		if silent {
			return nil
		}
		names := schemaNames()
		if jsonOut {
			docs := make([]map[string]string, 0, len(names))
			for _, n := range names {
				docs = append(docs, map[string]string{"name": n, "description": schemaDocs[n].description})
			}
			return emitJSON(cmd.OutOrStdout(), map[string]any{"schemas": docs})
		}
		out := cmd.OutOrStdout()
		ui.Fprintln(out, ui.AccentBoldStyle().Render("  Schema documents"))
		ui.Fprintln(out)
		tbl := ui.CompactTable().StyleFunc(ui.LabelValueStyleFunc())
		for _, n := range names {
			tbl = tbl.Row(n, schemaDocs[n].description)
		}
		ui.Fprintln(out, tbl.String())
		return nil
	},
}

var schemaGetCmd = &cobra.Command{
	Use:   "get <name>",
	Short: "Print one schema document",
	Long: `Print one schema document.

Renders as text by default and as JSON with --json, like every other
command. Both come from the same in-code registry, so the two renderings
cannot disagree, and neither can drift from the binary printing them.

Run 'truestamp schema list' for the available names.`,
	Args: cobra.ExactArgs(1),
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return schemaNames(), cobra.ShellCompDirectiveNoFileComp
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		name := strings.ToLower(strings.TrimSpace(args[0]))
		doc, ok := schemaDocs[name]
		if !ok {
			return fmt.Errorf("unknown schema %q, one of: %s", name, strings.Join(schemaNames(), " | "))
		}
		jsonOut, silent := outputMode(cmd)
		if silent {
			return nil
		}
		if jsonOut {
			return emitJSON(cmd.OutOrStdout(), withNote(doc.build(), doc.note))
		}
		doc.render(cmd.OutOrStdout())
		if doc.note != "" {
			ui.Fprintln(cmd.OutOrStdout(), ui.FaintStyle().Render("    "+doc.note))
		}
		return nil
	},
}

// A schema document has two renderings of one registry. Both read the
// registry directly rather than one deriving from the other, so neither
// can drift from it — and --json stays universal across the tree instead
// of this command being the exception that has to be remembered.
type schemaDoc struct {
	description string
	// note is one line of context declared ONCE and emitted in both
	// renderings. A footnote that existed only in the text form would be
	// prose the JSON consumer never sees, which is the asymmetry this
	// whole arrangement exists to avoid.
	note   string
	build  func() any
	render func(w io.Writer)
}

var schemaDocs = map[string]schemaDoc{
	"commands": {
		description: "The full command tree: every path, flag, type, default and enum",
		note: "A trailing / marks a group. --json adds every flag, type, default, " +
			"shorthand and closed value set.",
		build: func() any {
			return introspect.Walk(rootCmd, cliEnums(), false)
		},
		render: func(w io.Writer) {
			// An indented outline of every path. This is the one document
			// whose text form is genuinely different from --help: it shows
			// the whole shape at once rather than one level at a time.
			tree := introspect.Walk(rootCmd, cliEnums(), false)
			ui.Fprintln(w, ui.AccentBoldStyle().Render("  Command tree"))
			ui.Fprintln(w)
			var walk func(c introspect.Command, depth int)
			walk = func(c introspect.Command, depth int) {
				if depth > 0 {
					name := c.Path[strings.LastIndex(c.Path, " ")+1:]
					kind := ""
					if c.Group {
						kind = "/"
					}
					ui.Fprintf(w, "  %s%s%s\n",
						strings.Repeat("  ", depth), name, kind)
				}
				for _, sub := range c.Subcommands {
					walk(sub, depth+1)
				}
			}
			walk(tree, 0)
			ui.Fprintln(w)
		},
	},
	"algorithms": {
		description: "Hash algorithms accepted by `truestamp hash -a`",
		build: func() any {
			algs := hashing.Algorithms()
			out := make([]map[string]any, 0, len(algs))
			for _, a := range algs {
				out = append(out, map[string]any{
					"name":       a.Name,
					"size_bytes": a.Size,
					"aliases":    a.Aliases,
					"legacy":     a.Legacy,
				})
			}
			return map[string]any{"algorithms": out}
		},
		render: func(w io.Writer) {
			// Booleans render as their literal value, not as a marker or a
			// blank. A blank cell is indistinguishable from a missing one,
			// and it makes the text quietly carry less than the JSON.
			rows := [][]string{{"ALGORITHM", "BYTES", "ALIASES", "LEGACY"}}
			for _, a := range hashing.Algorithms() {
				rows = append(rows, []string{a.Name,
					fmt.Sprintf("%d", a.Size), strings.Join(a.Aliases, ", "),
					fmt.Sprintf("%v", a.Legacy)})
			}
			renderSchemaTable(w, "Hash algorithms", rows)
		},
	},
	"subject-types": {
		description: "The frozen proof subject type registry (name to wire code)",
		// A note describes THIS document's subject. It deliberately makes no
		// claim about what another command prints: the previous version said
		// `truestamp inspect` showed the code beside the name, and went stale
		// the moment inspect stopped reporting it. Behaviour is documented
		// next to the behaviour, in that command's own help.
		note: "The code is never on the wire: bundles carry the type NAME, in both JSON " +
			"and CBOR, and the server never returns the number. It exists only as the " +
			"t(2) field of the signature preimage, so this mapping is needed only when " +
			"reconstructing that payload by hand.",
		build: func() any {
			out := make([]map[string]any, 0, len(proofTypeValues))
			for _, name := range proofTypeValues {
				entry := map[string]any{"name": name}
				if code, ok := ptype.FromName(name); ok {
					entry["code"] = uint16(code)
				}
				out = append(out, entry)
			}
			return map[string]any{"subject_types": out}
		},
		render: func(w io.Writer) {
			rows := [][]string{{"SUBJECT TYPE", "WIRE CODE"}}
			for _, name := range proofTypeValues {
				code := ""
				if c, ok := ptype.FromName(name); ok {
					code = fmt.Sprintf("%d", uint16(c))
				}
				rows = append(rows, []string{name, code})
			}
			renderSchemaTable(w, "Subject types (frozen registry)", rows)
		},
	},
	"witnesses": {
		description: "Witness names accepted by `--witnesses`, and which are committed",
		note: "signing_key_event witnesses the signature and rides at the bundle's top level, " +
			"so the subject metadata never commits to it.",
		build: func() any {
			// One list with the distinguishing property on each entry,
			// rather than two lists the reader has to diff. The property
			// is derived from the registry, so it cannot drift from it.
			//
			// A witness is a public record that existed before the
			// submission. Four of the five are committed by the subject's
			// composite fingerprint, in subject.metadata.witnesses.
			// signing_key_event witnesses the signature instead, rides at
			// the bundle's top level, and is never in that metadata — which
			// is the whole difference between the two sets.
			out := make([]map[string]any, 0, len(proof.WitnessNames))
			for _, name := range proof.WitnessNames {
				out = append(out, map[string]any{
					"name":                          name,
					"committed_in_subject_metadata": proof.IsCommittedWitnessName(name),
				})
			}
			return map[string]any{"witnesses": out}
		},
		render: func(w io.Writer) {
			rows := [][]string{{"WITNESS", "COMMITTED IN SUBJECT METADATA"}}
			for _, name := range proof.WitnessNames {
				rows = append(rows, []string{name,
					fmt.Sprintf("%v", proof.IsCommittedWitnessName(name))})
			}
			renderSchemaTable(w, "Witnesses", rows)
		},
	},
	"exit-codes": {
		description: "What each process exit status means",
		build: func() any {
			return map[string]any{
				"exit_codes":               exitCodes,
				"upgrade_check_exit_codes": upgradeCheckExitCodes,
			}
		},
		render: func(w io.Writer) {
			renderSchemaTable(w, "Exit codes", exitCodeRows(exitCodes))
			renderSchemaTable(w, "upgrade --check --exit-code", exitCodeRows(upgradeCheckExitCodes))
		},
	},
}

// withNote attaches a document's note to its JSON form, so the note is
// declared once and neither rendering carries prose the other lacks.
func withNote(v any, note string) any {
	if note == "" {
		return v
	}
	m, ok := v.(map[string]any)
	if !ok {
		// A document whose top level is not a map (the command tree) keeps
		// its own shape; wrapping it would change the contract consumers
		// already parse.
		return v
	}
	out := make(map[string]any, len(m)+1)
	for k, val := range m {
		out[k] = val
	}
	out["note"] = note
	return out
}

// exitCode is one row of the process exit contract.
type exitCode struct {
	Code    int    `json:"code"`
	Meaning string `json:"meaning"`
}

// exitCodes is the single declaration of what this binary's exit statuses
// mean. The numbers come from the constants that actually produce them,
// so a change in behaviour cannot leave this describing the old contract,
// and both the JSON and the text rendering read this one slice rather
// than each carrying its own copy of the sentences.
var exitCodes = []exitCode{
	{0, "the command did what it was asked"},
	{1, "it did not: failed verification, network failure, invalid input, or any other runtime error"},
	{panicExitCode, "an unrecovered panic, matching Go's own convention"},
}

// upgradeCheckExitCodes is the opt-in encoding `upgrade --check
// --exit-code` uses. Same treatment: the numbers are the constants.
var upgradeCheckExitCodes = []exitCode{
	{checkExitUpToDate, "up to date"},
	{checkExitUpgradeAvail, "an upgrade is available"},
	{checkExitNetworkErr, "a network error prevented the check"},
	{checkExitPreRelease, "the latest release is a pre-release and will not auto-install"},
}

// exitCodeRows renders one exit-code table's rows, header first.
func exitCodeRows(list []exitCode) [][]string {
	rows := [][]string{{"CODE", "MEANING"}}
	for _, e := range list {
		rows = append(rows, []string{fmt.Sprintf("%d", e.Code), e.Meaning})
	}
	return rows
}

// renderSchemaTable prints a header plus a bordered table whose first row
// is treated as column labels.
func renderSchemaTable(w io.Writer, title string, rows [][]string) {
	tbl := ui.CompactTable().
		StyleFunc(ui.HeaderRowStyleFunc()).
		Rows(rows...)
	ui.Fprintln(w, ui.AccentBoldStyle().Render("  "+title))
	ui.Fprintln(w)
	ui.Fprintln(w, tbl.String())
	ui.Fprintln(w)
}

func schemaNames() []string {
	names := make([]string, 0, len(schemaDocs))
	for n := range schemaDocs {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// cliEnums is the registry of closed flag value sets. Cobra cannot model
// these, so they are declared here and fed to both `schema get commands`
// and shell completion, which means tab completion and the machine-
// readable description can never disagree about what a flag accepts.
func cliEnums() introspect.EnumValues {
	var algNames []string
	for _, a := range hashing.Algorithms() {
		algNames = append(algNames, a.Name)
	}
	byteEncodings := encoding.AllNames()

	// A bare flag name applies to EVERY command that has a flag by that
	// name. That is only safe when exactly one does, or when they all mean
	// the same thing — --type, --format and --to each mean different things
	// on different commands, so they are scoped by path.
	//
	// This is the same hazard internal/config's flagKeyMap had, where a
	// bare `json` mapped to verify.json for every command that registered
	// one. There it was inert; here it is not: an unscoped entry makes the
	// shell offer values the command rejects. TestSchema_NoUnscopedEnumForACollidingFlag
	// fails if a bare key is used for a name more than one command carries.
	return introspect.EnumValues{
		// Same meaning wherever they appear.
		"witnesses": append([]string{"all", "none"}, proof.WitnessNames...),
		"algorithm": algNames,
		"encoding":  {"hex", "base64", "base64url"},
		"style":     {"gnu", "bsd", "bare"},
		"log-level": {"debug", "info", "warn", "error"},

		// --source: an entropy source, the same vocabulary as the entropy_*
		// proof subject types.
		"truestamp entropy list|source":   entropy.Sources,
		"truestamp entropy latest|source": entropy.Sources,

		// --type: a proof subject type on two commands, an id shape on a third.
		"truestamp verify|type":     proofTypeValues,
		"truestamp proofs get|type": proofTypeValues,
		"truestamp convert id|type": {"auto", "ulid", "uuid7"},

		// --format: a wire format on one, a timestamp format on the other.
		"truestamp proofs get|format":   {"json", "cbor"},
		"truestamp convert time|format": {"rfc3339", "unix-s", "unix-ms", "unix-us", "unix-ns"},

		// --to: a wire format on one, a byte encoding on the other two.
		"truestamp proofs convert|to": {"json", "cbor"},
		"truestamp encode|to":         byteEncodings,
		"truestamp decode|to":         byteEncodings,
	}
}

// registerEnumCompletions wires the same registry into shell completion,
// so `truestamp verify --type <TAB>` offers the six subject types instead
// of returning nothing. Sharing one registry with `schema get commands`
// means completion and the machine-readable description cannot disagree
// about what a flag accepts.
func registerEnumCompletions(root *cobra.Command) {
	enums := cliEnums()
	var walk func(c *cobra.Command, path string)
	walk = func(c *cobra.Command, path string) {
		c.LocalFlags().VisitAll(func(f *pflag.Flag) {
			vals := introspect.LookupEnum(enums, path, f.Name)
			if vals == nil {
				return
			}
			_ = c.RegisterFlagCompletionFunc(f.Name,
				func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
					return vals, cobra.ShellCompDirectiveNoFileComp
				})
		})
		for _, sub := range c.Commands() {
			walk(sub, path+" "+sub.Name())
		}
	}
	walk(root, root.Name())
}

func init() {
	addRecordOutputFlags(schemaListCmd)
	addRecordOutputFlags(schemaGetCmd)
	schemaCmd.AddCommand(schemaListCmd)
	schemaCmd.AddCommand(schemaGetCmd)
	schemaCmd.GroupID = groupOther
	rootCmd.AddCommand(asGroup(schemaCmd))
}
