// Copyright (c) 2019-2026 Truestamp, Inc.
// SPDX-License-Identifier: MIT

package verify

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/truestamp/truestamp-cli/internal/external"
	"github.com/truestamp/truestamp-cli/internal/proof/ptype"
)

// Entropy subject types (t = 30, 31, 32) used to have no signed artifact in
// this repo. Every other subject type did: item.json, block.json and the
// Appendix D vector all carry real signatures, so their tests exercise E.16
// for real. The entropy path was exercised only by hand-built bundles that
// must run with --skip-signatures, which removes the one check that makes a
// proof a proof.
//
// The three fixtures below close that gap. They are NOT downloads from the
// production service: they are generated by
// testdata/fixtures/gen_entropy_fixtures.exs, an independent Elixir
// re-implementation of the derivation chain that signs with the same fixed,
// published illustrative Ed25519 seed (32 bytes of 0x42) that
// truestamp-v2/whitepaper/proof_vectors.exs signs the Appendix D vector with.
// So:
//
//   - E.16 runs and passes here. That is the whole point.
//   - E.17 does not: the illustrative key is not in Truestamp's keyring, so
//     Key Binding reports skip. That is correct and expected, and is what
//     appendix-d-item.json already does.
//   - The bundles are derived by Elixir and verified by Go, so a fixture that
//     passes cannot merely encode a Go bug. The generator's own self-check
//     re-derives each bundle from its emitted bytes alone, and
//     truestamp-v2/whitepaper/verify_proof.exs reports VERDICT: PASSED over
//     all three.
//
// Regenerate with (from the repo root):
//
//	elixir -pa ../truestamp-v2/_build/dev/lib/jcs/ebin \
//	  internal/verify/testdata/fixtures/gen_entropy_fixtures.exs
var entropyFixtures = []struct {
	name string
	file string
	code ptype.Code
}{
	{"entropy_nist", "entropy-nist.json", ptype.EntropyNIST},
	{"entropy_stellar", "entropy-stellar.json", ptype.EntropyStellar},
	{"entropy_bitcoin", "entropy-bitcoin.json", ptype.EntropyBitcoin},
}

// entropyFixtureBytes returns the fixture bytes. The file is committed, so an
// absent one is a failure and not a skip: a silently skipped suite is exactly
// the state this fixture set exists to leave behind.
func entropyFixtureBytes(t *testing.T, name string) []byte {
	t.Helper()
	path := filepath.Join("testdata", "fixtures", name)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v (regenerate with testdata/fixtures/gen_entropy_fixtures.exs)", path, err)
	}
	return data
}

// TestEntropyFixture_VerifiesWithSignatures is the check the hand-built
// bundles cannot make: run the real pipeline over a real bundle with the
// signature check ENABLED. Offline, so the E.21 re-fetch and the two
// commitment confirmations report skip rather than reaching the network,
// but E.9, E.10's 0x21 and 0x23 derivations, E.13, E.14, E.15 and E.16 all
// run for real.
func TestEntropyFixture_VerifiesWithSignatures(t *testing.T) {
	for _, f := range entropyFixtures {
		t.Run(f.name, func(t *testing.T) {
			data := entropyFixtureBytes(t, f.file)

			r, err := RunFromBytes(data, f.file, Options{SkipExternal: true})
			if err != nil {
				t.Fatalf("parse/run: %v", err)
			}
			if !r.Passed() {
				for _, s := range r.Steps {
					if s.Status == StatusFail {
						t.Errorf("fail: %s | %s | %s", s.Group, s.Category, s.Message)
					}
				}
				t.Fatal("a signed entropy fixture must verify offline")
			}

			// The signature step must have actually run. A fixture that
			// verified only because signatures were skipped would defeat
			// the purpose of committing it.
			var sigRan bool
			for _, s := range r.Steps {
				if s.Group == groupProof && s.Status == StatusPass {
					sigRan = true
				}
			}
			if !sigRan {
				t.Error("no passing Proof Signature step: E.16 did not run, so this fixture proves nothing a --skip-signatures run would not")
			}

			// E.17 is not established by this run, but note WHY: the skip
			// here is caused by SkipExternal, which short-circuits
			// verifyKeyBinding before any lookup. Asserting `skip` under
			// this flag would hold for any bundle whatsoever and would
			// say nothing about the illustrative key. The real claim, that
			// the key does not bind to Truestamp, is established against a
			// live keyring in TestEntropyFixture_IllustrativeKeyIsNotBound.
			if st, ok := stepStatus(r, groupKeyBinding); !ok || st != StatusSkip {
				t.Errorf("Key Binding = %v (present=%v), want skip under --skip-external", st, ok)
			}
		})
	}
}

// TestEntropyFixture_SubjectTypeAndDerivations pins that the fixture is the
// type it claims and that the entropy-specific derivations are the ones
// that ran. The 0x21 entropy hash and 0x23 observation hash are the two
// steps that distinguish an entropy subject from an item.
func TestEntropyFixture_SubjectTypeAndDerivations(t *testing.T) {
	for _, f := range entropyFixtures {
		t.Run(f.name, func(t *testing.T) {
			data := entropyFixtureBytes(t, f.file)

			r, err := RunFromBytes(data, f.file, Options{SkipExternal: true})
			if err != nil {
				t.Fatalf("parse/run: %v", err)
			}
			if got, want := r.SubjectType, ptype.Name(f.code); got != want {
				t.Errorf("SubjectType = %q, want %q: fixture is not the type its filename claims", got, want)
			}

			// Entropy subjects derive through 0x21/0x23, never the item
			// 0x11/0x13 pair. The prefixes are spec constants, not
			// wording, so naming them is a real assertion about which
			// derivation ran: an entropy bundle that reported "Claims
			// hash derived (0x11)" would be running the item path over
			// entropy data and would still reach a self-consistent
			// answer, which is the failure mode a group-only count
			// cannot see.
			var subjectDataPasses int
			for _, s := range r.Steps {
				if s.Group == groupSubjectData && s.Status == StatusPass {
					subjectDataPasses++
				}
			}
			if subjectDataPasses == 0 {
				t.Error("no passing Subject Data step: the 0x21/0x23 derivations did not run")
			}
			msgs := stepMessages(r)
			for _, want := range []string{"0x21", "0x23"} {
				if !strings.Contains(msgs, want) {
					t.Errorf("no Subject Data step names %s: the entropy derivations did not run:\n%s", want, msgs)
				}
			}
			for _, unwanted := range []string{"0x11", "0x13"} {
				if strings.Contains(msgs, unwanted) {
					t.Errorf("a step names the item prefix %s: an entropy subject must never derive through the item path:\n%s", unwanted, msgs)
				}
			}

			// The inclusion walk is what binds this observation to the
			// block the signature covers. All three fixtures are leaves
			// of one tree, so a passing walk here is a real sibling path
			// rather than a degenerate single-leaf tree.
			if st, ok := stepStatus(r, groupInclusion); !ok || st != StatusPass {
				t.Errorf("Inclusion Proof = %v (present=%v), want pass", st, ok)
			}

			// A bundle whose s.d does not match the shape
			// parseEntropySubject reads still verifies cryptographically
			// — the hash is over the raw bytes either way — but renders a
			// blank Entropy Observation section. Assert the parsed detail
			// so a future s.d reshuffle is caught here rather than by
			// someone noticing an empty report.
			es := r.EntropySubject
			if es.RawSource != ptype.Name(f.code) {
				t.Errorf("EntropySubject.RawSource = %q, want %q", es.RawSource, ptype.Name(f.code))
			}
			if es.CapturedAt == "" {
				t.Error("EntropySubject.CapturedAt is empty: s.d does not carry the timestamp field this type's parser reads")
			}
			switch f.code {
			case ptype.EntropyNIST:
				if es.PulseIndex == 0 || es.ChainIndex == 0 || es.OutputValue == "" {
					t.Errorf("NIST detail not parsed from s.d: pulse=%d chain=%d outputValue=%q", es.PulseIndex, es.ChainIndex, es.OutputValue)
				}
				// The real beacon publishes a 64-byte output value.
				if got := len(es.OutputValue); got != 128 {
					t.Errorf("outputValue is %d hex characters, want 128 (64 bytes, the beacon's width)", got)
				}
			case ptype.EntropyStellar:
				if es.LedgerSequence == 0 || es.LedgerHash == "" {
					t.Errorf("Stellar detail not parsed from s.d: sequence=%d hash=%q", es.LedgerSequence, es.LedgerHash)
				}
			case ptype.EntropyBitcoin:
				if es.BlockHeight == 0 || es.BlockHash == "" || es.BlockTime == 0 {
					t.Errorf("Bitcoin detail not parsed from s.d: height=%d hash=%q time=%d", es.BlockHeight, es.BlockHash, es.BlockTime)
				}
			}
		})
	}
}

// TestEntropyFixture_TypeCodeIsBoundIntoTheSignature is the check that
// needs three signed artifacts to exist at once.
//
// The subject type code travels as a uint16 inside the signed payload, so
// the three fixtures differ in that byte and in nothing else the signature
// covers except the subject hash. Rewriting `t` to a sibling entropy code
// must therefore break E.16. Without this, a generator that built every
// payload with a hardcoded `t` would still produce one fixture that
// verifies, and the other two would fail for a reason no test could name.
func TestEntropyFixture_TypeCodeIsBoundIntoTheSignature(t *testing.T) {
	all := []ptype.Code{ptype.EntropyNIST, ptype.EntropyStellar, ptype.EntropyBitcoin}

	for _, f := range entropyFixtures {
		t.Run(f.name, func(t *testing.T) {
			for _, wrong := range all {
				if wrong == f.code {
					continue
				}
				tampered := rewriteBundleField(t, entropyFixtureBytes(t, f.file), "t", uint16(wrong))

				r, err := RunFromBytes(tampered, f.file, Options{SkipExternal: true})
				if err != nil {
					// A parse refusal is an acceptable rejection too:
					// what must never happen is a clean verification.
					continue
				}
				if st, ok := stepStatus(r, groupProof); !ok || st != StatusFail {
					t.Errorf("t rewritten %d -> %d: Proof Signature = %v (present=%v), want fail — the type code is not bound into the signed payload",
						uint16(f.code), uint16(wrong), st, ok)
				}
				if r.Passed() {
					t.Errorf("t rewritten %d -> %d: the proof still verified", uint16(f.code), uint16(wrong))
				}
			}
		})
	}
}

// TestEntropyFixture_SourceUnreachableIsSkip pins the E.21 grading that the
// conformance work introduced: an unreachable upstream must report skip,
// never fail, so a NIST or Blockstream outage cannot turn a sound proof
// into a forged-looking one. Package-level tests already assert this
// against the fetchers; this asserts it through the whole pipeline on a
// signed bundle.
func TestEntropyFixture_SourceUnreachableIsSkip(t *testing.T) {
	for _, f := range entropyFixtures {
		t.Run(f.name, func(t *testing.T) {
			// Point EVERY external endpoint at a closed port, not just
			// the keyring: this run has SkipExternal off, so the entropy
			// re-fetch and both commitment lookups would otherwise reach
			// the real NIST, Horizon and Blockstream. That made the test
			// depend on live network state, and on hosts with network
			// access it decided the outcome from whatever those services
			// answered about illustrative indices — which is the one
			// thing this test must not measure.
			unreachableExternals(t)

			r, err := RunFromBytes(entropyFixtureBytes(t, f.file), f.file, Options{
				KeyringURL: "http://127.0.0.1:1/keyring.json",
			})
			if err != nil {
				t.Fatalf("parse/run: %v", err)
			}
			for _, s := range r.Steps {
				if s.Group == groupEntropySource && s.Status == StatusFail {
					t.Errorf("unreachable entropy source reported fail, want skip: %s", s.Message)
				}
			}
			if st, ok := stepStatus(r, groupEntropySource); !ok || st != StatusSkip {
				t.Errorf("Entropy Source = %v (present=%v), want skip", st, ok)
			}
			if !r.Passed() {
				for _, s := range r.Steps {
					if s.Status == StatusFail {
						t.Errorf("fail: %s | %s", s.Group, s.Message)
					}
				}
				t.Fatal("an offline run must not fail a sound proof (E.22: a skipped external check must not fail a proof)")
			}
		})
	}
}

// TestEntropyFixture_SourceGrading runs E.21's two decisive branches through
// the shipped pipeline rather than against the fetchers directly: the
// upstream answers, and either it echoes the observation the bundle carries
// or it contradicts it.
//
// Only a mismatch may fail. Agreement is the only thing that may pass, and
// only for the values actually compared — which is why the stub is built
// from the fixture's own s.d rather than from constants: a subject-shape
// change that stopped the verifier from reading a field would otherwise
// leave this test passing on an empty comparison.
func TestEntropyFixture_SourceGrading(t *testing.T) {
	for _, f := range entropyFixtures {
		t.Run(f.name, func(t *testing.T) {
			for _, tc := range []struct {
				name    string
				agree   bool
				want    Status
				wantSub string
			}{
				{"upstream agrees", true, StatusPass, "confirmed"},
				{"upstream contradicts the observation", false, StatusFail, "mismatch"},
			} {
				t.Run(tc.name, func(t *testing.T) {
					data := entropyFixtureBytes(t, f.file)
					entropySourceStub(t, f.code, subjectData(t, data), tc.agree)

					r, err := RunFromBytes(data, f.file, Options{
						KeyringURL: "http://127.0.0.1:1/keyring.json",
					})
					if err != nil {
						t.Fatalf("parse/run: %v", err)
					}
					st, ok := stepStatus(r, groupEntropySource)
					if !ok {
						t.Fatalf("no Entropy Source step:\n%s", stepMessages(r))
					}
					if st != tc.want {
						t.Errorf("Entropy Source = %v, want %v:\n%s", st, tc.want, stepMessages(r))
					}
					if msg := groupMessage(r, groupEntropySource); !strings.Contains(strings.ToLower(msg), tc.wantSub) {
						t.Errorf("Entropy Source message = %q, want it to mention %q", msg, tc.wantSub)
					}
				})
			}
		})
	}
}

// --- helpers ---

// stepStatus returns the status of the last step filed under group. Steps in
// a group are appended in order and the entropy groups emit one row, so
// "last" is "the one".
func stepStatus(r *Report, group string) (Status, bool) {
	var (
		st Status
		ok bool
	)
	for _, s := range r.Steps {
		if s.Group == group {
			st, ok = s.Status, true
		}
	}
	return st, ok
}

// groupMessage returns the last message filed under group.
func groupMessage(r *Report, group string) string {
	var msg string
	for _, s := range r.Steps {
		if s.Group == group {
			msg = s.Message
		}
	}
	return msg
}

// rewriteBundleField replaces one top-level key of a bundle and re-encodes
// it. Round-tripping through a map is safe here because every value the
// pipeline hashes (s.d, and the raw hex/base64 strings) survives it
// byte-identically: s.d is re-canonicalized with JCS before hashing, so key
// order is irrelevant, and Go's encoder does not rewrite the string fields.
func rewriteBundleField(t *testing.T, bundle []byte, key string, value any) []byte {
	t.Helper()
	var m map[string]json.RawMessage
	if err := json.Unmarshal(bundle, &m); err != nil {
		t.Fatalf("unmarshal bundle: %v", err)
	}
	raw, err := json.Marshal(value)
	if err != nil {
		t.Fatalf("marshal %s: %v", key, err)
	}
	m[key] = raw
	out, err := json.Marshal(m)
	if err != nil {
		t.Fatalf("marshal bundle: %v", err)
	}
	return out
}

// subjectData returns the bundle's s.d as a decoded map.
func subjectData(t *testing.T, bundle []byte) map[string]any {
	t.Helper()
	var b struct {
		S struct {
			D map[string]any `json:"d"`
		} `json:"s"`
	}
	if err := json.Unmarshal(bundle, &b); err != nil {
		t.Fatalf("unmarshal bundle: %v", err)
	}
	if len(b.S.D) == 0 {
		t.Fatal("bundle carries no s.d")
	}
	return b.S.D
}

// unreachableExternals points every external endpoint the pipeline can reach
// at a closed port, so the whole run is hermetic and every lookup fails as
// unavailable rather than as a disagreement.
func unreachableExternals(t *testing.T) {
	t.Helper()
	redirectExternals(t, "http://127.0.0.1:1")
}

// redirectExternals repoints the five external base URLs and restores them
// on cleanup. They are package-level vars, so this must not run in parallel
// with anything else that touches them.
func redirectExternals(t *testing.T, base string) {
	t.Helper()
	origNIST := external.NISTBeaconURL
	origPublic := external.HorizonPublicURL
	origTestnet := external.HorizonTestnetURL
	origMainnet := external.BlockstreamMainnetURL
	origBTCTest := external.BlockstreamTestnetURL

	external.NISTBeaconURL = base
	external.HorizonPublicURL = base
	external.HorizonTestnetURL = base
	external.BlockstreamMainnetURL = base
	external.BlockstreamTestnetURL = base

	t.Cleanup(func() {
		external.NISTBeaconURL = origNIST
		external.HorizonPublicURL = origPublic
		external.HorizonTestnetURL = origTestnet
		external.BlockstreamMainnetURL = origMainnet
		external.BlockstreamTestnetURL = origBTCTest
	})
}

// entropySourceStub stands up the upstream this subject type re-fetches and
// points the pipeline at it. When agree is false exactly one compared field
// is perturbed, so the run reaches the comparison and disagrees there rather
// than failing earlier for an unrelated reason.
//
// Bitcoin's hash is deliberately never the perturbed field: the lookup is BY
// hash, so an answer about a different block is graded skip (an upstream
// defect, not the bundle's). Height is the operand that can genuinely
// contradict the observation.
func entropySourceStub(t *testing.T, code ptype.Code, d map[string]any, agree bool) {
	t.Helper()

	var body any
	switch code {
	case ptype.EntropyNIST:
		pulse, _ := d["pulse"].(map[string]any)
		if pulse == nil {
			t.Fatal("NIST subject data carries no pulse object")
		}
		out, _ := pulse["outputValue"].(string)
		if !agree {
			out = strings.Repeat("00", 64)
		}
		body = map[string]any{"pulse": map[string]any{
			"chainIndex":  pulse["chainIndex"],
			"pulseIndex":  pulse["pulseIndex"],
			"outputValue": out,
			"timeStamp":   pulse["timeStamp"],
			"version":     pulse["version"],
		}}

	case ptype.EntropyStellar:
		hash, _ := d["hash"].(string)
		if !agree {
			hash = strings.Repeat("00", 32)
		}
		body = map[string]any{
			"sequence":  d["sequence"],
			"hash":      hash,
			"closed_at": d["closed_at"],
		}

	case ptype.EntropyBitcoin:
		height, _ := d["height"].(float64)
		if !agree {
			height++
		}
		body = map[string]any{
			"id":        d["hash"],
			"height":    int(height),
			"timestamp": d["time"],
		}

	default:
		t.Fatalf("no entropy stub for type %d", uint16(code))
	}

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		// Only the entropy lookup is stubbed. The commitment lookups
		// share these hosts, and answering them from here would either
		// fabricate a confirmation or manufacture a definitive 404; a
		// 503 keeps them graded unavailable, which is what they are.
		if !isEntropyLookupPath(code, req.URL.Path) {
			w.WriteHeader(http.StatusServiceUnavailable)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(body)
	}))
	t.Cleanup(srv.Close)

	redirectExternals(t, srv.URL)
}

// isEntropyLookupPath reports whether path is the entropy re-fetch endpoint
// for this subject type, as opposed to a commitment lookup on the same host.
func isEntropyLookupPath(code ptype.Code, path string) bool {
	switch code {
	case ptype.EntropyNIST:
		return strings.Contains(path, "/pulse/")
	case ptype.EntropyStellar:
		return strings.HasPrefix(path, "/ledgers/")
	case ptype.EntropyBitcoin:
		return strings.HasPrefix(path, "/block/")
	}
	return false
}

// TestEntropyFixture_IllustrativeKeyIsNotBound establishes the claim the
// offline test cannot: that the fixtures' signing key is NOT a Truestamp
// key. Under --skip-external the Key Binding step short-circuits to skip
// before any lookup, so that skip is caused by the flag and holds for any
// bundle. Here the lookup actually runs, against a keyring that answers
// and does not list the illustrative key id, and E.17 must report a
// failure rather than quietly passing.
//
// This is the assertion that would break if the illustrative seed were
// ever published as a real Truestamp signing key: these fixtures would
// then bind, and a test fixture would carry production trust.
func TestEntropyFixture_IllustrativeKeyIsNotBound(t *testing.T) {
	// A well-formed keyring that simply does not contain the fixtures' kid.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(external.KeyringResponse{
			Version: "1",
			Keys: []external.KeyringKey{{
				KeyID:     "00000000",
				PublicKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
			}},
		})
	}))
	defer srv.Close()

	for _, f := range entropyFixtures {
		t.Run(f.name, func(t *testing.T) {
			data := entropyFixtureBytes(t, f.file)

			// Only the keyring is reachable; every other upstream is dead,
			// so this measures E.17 alone and not the entropy re-fetch.
			redirectExternals(t, "http://127.0.0.1:1")

			r, err := RunFromBytes(data, f.file, Options{KeyringURL: srv.URL})
			if err != nil {
				t.Fatalf("parse/run: %v", err)
			}

			st, ok := stepStatus(r, groupKeyBinding)
			if !ok {
				t.Fatal("no Key Binding step: E.17 must be reported, not omitted")
			}
			if st != StatusFail {
				t.Errorf("Key Binding = %v, want fail: a keyring that answered and does not list %s must not bind it. If this now passes, the illustrative signing key has been published as a real Truestamp key and these fixtures carry production trust", st, "the fixtures' kid")
			}
		})
	}
}
