name: Release Dev

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Build
        run:
          echo ${{ github.sha }} > RELEASE.txt
          make build
      - name: Test
        run: cat RELEASE.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            RELEASE.txt
            build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
